import './globals.css';
import Header from './compornents/Header/Header';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <body className='wrapper'>
        <Header />
        {children}
        <footer >
          <p>2023 minori's portfolio</p>
        </footer>
      </body>
    </html>
  )
}
