import { Metadata } from 'next';
import './globals.css';
import Header from './compornents/Header/Header';

export const metadata = {
  title: 'Portfolio | Minori Komeichi',
  description: 'Generated by create next app',
  robots: 'noindex',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <body className='wrapper'>
        <Header />
        {children}
        <footer >
          <p>2023 minori&apos;s portfolio</p>
        </footer>
      </body>
    </html>
  )
}
