export const articles = [
    {
        title: '老人施設紹介事業のランディングページ(架空)',
        which: 'web',
        tags: ['Illustrator', 'Figma','HTML', 'CSS' ],
        src: '/himawari.jpg',
        concept: '高齢者にもわかりやすいLPにする',
        time: '7月(約30時間)',
        url: 'http://mkp0rtfolio.html.xdomain.jp/himawari/index.html',
        field: 'コンテンツの構想 / ロゴ作成 / デザインカンプ作成 / コーディング',
        point: ['高齢者にも分かりやすく操作できることを意識し、ハンバーガーメニューはメニューと表記し、文字サイズも大きめに設定。画面酔いも考慮し、アニメーションの多様は控えた。', 'ロゴの色に合わせて、配色はオレンジで統一し、暖かい雰囲気を出すことを意識した。', 'レスポンシブ対応では文字サイズやレイアウトをタブレットサイズに合わせてみやすくなるよう、細かく確認しながら実装しました。'],
    },
    {
        title: 'カフェのホームページ（架空・学内課題)',
        which: 'web',
        tags: ['HTML', 'CSS'],
        src: '/kujira.jpg',
        concept: '見やすいコーディングに取り組む',
        time: '7月(約6時間)',
        url: 'http://mkp0rtfolio.html.xdomain.jp/kujira/index.html',
        field: 'コーディング',
        point: ['デザインカンプに沿った表示となるように、何度もデザインカンプと表示画面を確認しながらコーディングを行い微修正を加えて仕上げました。', 'レスポンシブにも対応させ、コードはリーダブルコードとなるよう意識しながら書き上げました。'],
    },
    {
        title: '登山ツアーのランディングページ(架空)',
        which: 'web',
        tags: ['adobeXD', 'HTML', 'CSS', 'Javascript'],
        src: '/tours.jpg',
        concept: '北海道の山に興味を持ってもらう',
        time: '8月(約35時間)',
        url: '',
        field: 'コンテンツの構想 / ロゴ作成 / デザインカンプ作成 / コーディング',
        point: ['夏の山ということで、青と赤を基調とした配色にした。', 'レスポンシブ対応では、写真の配置を変更し、端末での見やすさも意識した。', '簡単にLPの全体像が掴めるように、各ツアーの詳細はアコーディオンパネルに収納した。', '期間を1週間として、優先順位を考えながら必要な機能をつけていきました。', '前回(高齢者向け住宅紹介のLP)の制作でJavascriptに興味を持ったため、Javascriptの学習も兼ねて、トップページのスライドやスライド時のポップアップ表示などはJavascriptを使用してみました。'],
    },
    {
        title: 'カメラマンの名刺(架空)',
        which: 'design',
        tags: ['Illustrator',],
        src: '/businesscard.jpg',
        concept: '親しみやすさを出す',
        time: '5月(約5時間)',
        field: 'デザイン',
        point: ['40代の強面男性をイメージして作成しました。', 'イラストから名前を連想できるように、亀を取り入れました。', '写真のシャッターを連想させるような背景を取り入れました。'],
    },
    {
        title: '店内ポップ(架空)',
        which: 'design',
        tags: ['Illustrator',],
        src: '/pop.jpg',
        concept: 'SALEしていることを周知する',
        time: '6月(約6時間)',
        field: 'デザイン',
        point: ['ポップなアパレル店をイメージして作成しました。', '夏のセールだったので、爽やかな配色にしました。'],
    },
    {
        title: 'オンライン英会話のバナー(架空)',
        which: 'design',
        tags: ['Illustrator', 'Photoshop'],
        src: '/english.jpg',
        concept: '20～30代をターゲットに興味を持ってもらう',
        time: '5月(約6時間)',
        field: 'デザイン',
        point: ['オンラインなので、自宅で利用しているイメージがでるように背景をリビングの写真にしました。', '気軽さや信頼性を表現するために、フレンドリーな男性の写真を載せました。'],
    },
    {
        title: 'イタリアン居酒屋のショップカード(架空)',
        which: 'design',
        tags: ['Illustrator', 'Photoshop'],
        src: '/shopcard.jpg',
        concept: 'ワインとイタリア料理を楽しめる居酒屋というイメージを持てるようにする',
        time: '6月(約6時間)',
        field: 'デザイン',
        point: ['イタリア料理のお店ということが一目で分かるように、表面と裏面に国旗の色を取り入れました。', '居酒屋という雰囲気がでるように暗めの色を使い、背景の素材はPhotosyopで作りました。'],
    },
    {
        title: '母の日のカード',
        which: 'design',
        tags: ['Photoshop',],
        src: '/mothersday.jpg',
        concept: '母の日ということを周知する',
        time: '4月(約6時間)',
        field: 'デザイン',
        point: ['花束はフリー画像を加工して作成しました。', '母という暖かさや優しさを連想しピンクを基調とした配色にしました。'],
    },
    {
        title: '仮想通貨のバナー(架空)',
        which: 'design',
        tags: ['Illustrator', 'Photoshop'],
        src: '/coin.jpg',
        concept: 'アイキャッチを大切にする',
        time: '7月(5時間)',
        field: 'デザイン',
        point: ['潜在的に興味を持っていた人をターゲットに、まずは目に入るということを優先にして作成しました。', '背景はIllustratorで作成しました。'],
    },
    // {
    //     title: '自身のポートフォリオサイト',
    //     which: 'web',
    //     tags: '',
    //     src: '',
    //     concept: '',
    //     time: '',
    //     url: '',
    //     field: ['', ''],
    //     point: ['', ''],
    // },
    // {
    //     title: '最終課題',
    //     which: 'web',
    //     tags: '',
    //     src: '',
    //     concept: '',
    //     time: '',
    //     field: ['', ''],
    //     point: ['', ''],
    // },

]